### PR TITLE
add support for ffmpeg 6.1

### PR DESCRIPTION
**Pull request by Simulping**
title says it all, prolly missing some stuff here and there.
idk i just want to get av-metrics working again

### CODE REVIEW

**Comment by FreezyLemon** [comment]
Can you add  an `ffmpeg_6_1` entry in build.rs (ffmpeg_lavc_versions)? Would also be good to have support for 6.1 in the CI scripts, but maybe out of scope for this PR

**Comment by shssoichiro** [comment]
+1 for FreezyLemon's suggestions. Also seems like the CI is mad because of formatting.

**Comment by FreezyLemon** [comment]
The CI script for FFmpeg 6.0 seems to be borked. The docker images have 6.0 and 6.1 releases now, removing the manual build job should work..

So removing this: 

https://github.com/shssoichiro/ffmpeg-the-third/blob/1af767b881e1c895a21a83887d03f9b15984f2bb/.github/workflows/build.yml#L43-L73

And instead adding `6.0` and `6.1` to this list:
https://github.com/shssoichiro/ffmpeg-the-third/blob/1af767b881e1c895a21a83887d03f9b15984f2bb/.github/workflows/build.yml#L16

**Comment by Simulping** [comment]
@shssoichiro yeah sure, hold on.

**Comment by shssoichiro** [comment]
The CI seems to be reporting there are some more enum items missing in ffmpeg 6.1: https://github.com/shssoichiro/ffmpeg-the-third/actions/runs/7795746682/job/21299726418?pr=13

**Comment by FreezyLemon** [comment]
@Simulping Do you still want to update this PR? If not, I'll take a look, I suppose...

**Pull request closed without merging**
