### PR TITLE
Specify MSRV & verify in CI

### PR DESCRIPTION
**Pull request by FreezyLemon**
An MSRV of 1.61.0 ([May 2022](https://releases.rs/docs/1.61.0/)) is pretty cheap to fulfill at the moment. The only dependency affected by this is `regex`, which is only a transitive dependency of `bindgen` and probably not in dire need of recent versions.

### CODE REVIEW

**Comment by shssoichiro** [comment]
I've never seen this "Cargo.lock.MSRV" before. Could you give a tl;dr of why this is needed?

**Comment by shssoichiro** [comment]
Hmm... I have mixed feelings about it. It's better for users who are on the latest Rust version, but does add an extra step, which isn't directly obvious, for users that are on the MSRV, if I'm understanding correctly. Which, to be sure I'm understanding correctly: Does this mean users who are on MSRV have to copy the Cargo.lock.MSRV over to Cargo.lock in order to compile?

**Comment by FreezyLemon** [comment]
> Does this mean users who are on MSRV have to copy the Cargo.lock.MSRV over to Cargo.lock in order to compile?

Yes, or at least `cargo build` might not run OOTB without further work (copying the Cargo.lock.MSRV or using `cargo build -Zmsrv-policy` or manually resolving MSRV problems). This is still better than not having a `rust-version` in the manifest at all.

> Hmm... I have mixed feelings about it. It's better for users who are on the latest Rust version, but does add an extra step, which isn't directly obvious, for users that are on the MSRV, if I'm understanding correctly.

Yes, that's the gist of it. We could document a how-to for people caring about MSRV if that helps.

What would your preferred alternative to this approach be?

**Comment by shssoichiro** [comment]
The way I've typically handled it in the past is to simply hold back dependencies that would break MSRV. To be fair, I haven't liked that approach much because there are a lot of crates in the Rust ecosystem that don't consider breaking MSRV to be a breaking change, which causes a lot of pain for this approach.

I think this approach works, but we should add a section to the Readme for how to compile with it.

**Comment by FreezyLemon** [comment]
I added a section to the README. I just noticed that I added "Increases in MSRV will result in a semver MINOR version increase." without thinking too much about it. Is that fine for you? It seems to be the accepted way of doing it, but you've mentioned your annoyance about it being non-breaking a few times before.

**Comment by shssoichiro** [comment]
Looks like a spurious download failure

**Review by shssoichiro — APPROVED** [review]

**Pull request merged**
